export default {
    TRADE_VISIBILITY: 'TRADE_VISIBILITY',
    CLEAR_REDUX_STATE: 'CLEAR_REDUX_STATE',
    GET_HOLDING_BEGIN: 'GET_HOLDING_BEGIN',
    GET_HOLDING_SUCCESS: 'GET_HOLDING_SUCCESS',
    GET_HOLDING_FAILURE: 'GET_HOLDING_FAILURE',
    GET_COIN_MARKET_BEGIN: 'GET_COIN_MARKET_BEGIN',
    GET_COIN_MARKET_SUCCESS: 'GET_COIN_MARKET_SUCCESS',
    GET_COIN_MARKET_FAILURE: 'GET_COIN_MARKET_FAILURE',
}